GET http://localhost:3001/api/patients

###

POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "ANDRES CARRILLO",
  "dateOfBirth": "1985-04-28",
  "ssn": "123654",
  "gender": "male",
  "occupation": "Developer"
}

###

GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667
